ALTER TABLE executions ADD COLUMN IF NOT EXISTS target_group_id BIGINT;
ALTER TABLE executions ADD COLUMN IF NOT EXISTS browser_type VARCHAR(50);
ALTER TABLE executions ADD COLUMN IF NOT EXISTS browser_version VARCHAR(50);

ALTER TABLE schedulers ADD COLUMN IF NOT EXISTS target_group_id BIGINT;
ALTER TABLE schedulers ADD COLUMN IF NOT EXISTS browser_type VARCHAR(50);
ALTER TABLE schedulers ADD COLUMN IF NOT EXISTS browser_version VARCHAR(50);

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS browser_type VARCHAR(50);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS browser_version VARCHAR(50);
